### ISSUE TITLE
vector tiles map: Hintergrundkarte

### ISSUE THREAD

**Issue by joshinils** [gislars/strassenraum-berlin#15]
they are all on by default, why? this makes the page loading slow and looks weird when they load in one by one changing in the background.

also, the toggle action is not obvious enough in the menu, there should be a bigger difference like a checkbox changing state other than a slight difference in shade of gray

**Comment by joshinils** [comment]
what is the default layer called which can not be toggled off?

**Comment by tordans** [comment]
**loading:** agreed, that is bad; no idea why it happens for now…

**toggle:** agreed; I will likely use a [radio button group layout](https://tailwindui.com/components/application-ui/forms/radio-groups)

**default layer:** there is more than one. they are listed in the html file right in the script tag. What is your use case?

**Comment by joshinils** [comment]
ah, MapLibre.
i just played with the background layers, and it is always in the background, so maybe you can also add it as an item in the list.

**Comment by tordans** [comment]
The initial loading is fixed. Will close this ticket. Other improvements will follow over time.
