### ISSUE TITLE
link zu github führt nicht hierhin

### ISSUE THREAD

**Issue by joshinils** [gislars/strassenraum-berlin#22]
in der sidebar links führt zu https://github.com/tordans/parkraum.osm-verkehrswende.org

**Comment by tordans** [comment]
Das ist formal auch richtig, denn es ist das Repo der Webseite.
Wir haben jetzt angefangen, in diesem Repo alle mögliche zu besprechen, was nicht nur die Daten, sondern auch die Funktionen der Seite angeht.

Meiner Erfahrung nach ist es fast nicht möglich, so etwas sauber zu trennen. Ich beobachte das mal und schaue, wie ich die Nutzer:innen zukünftig leite.

**Comment by tordans** [comment]
Es gibt jetzt eine eigene Seite, die die verschiedenen Orte referenziert.
