### ISSUE TITLE
Missing parking lanes on bridges

### ISSUE THREAD

**Issue by SupaplexOSM** [gislars/strassenraum-berlin#29]
Es sieht so aus, als würden zur Zeit Parkstreifen auf Brücken fehlen, z.B. https://parkraum.osm-verkehrswende.org/project-vector-tiles/#17.48/52.467795/13.436263 oder https://parkraum.osm-verkehrswende.org/project-vector-tiles/#17.05/52.46599/13.421531.

**Comment by joshinils** [comment]
https://www.openstreetmap.org/way/7729029
https://parkraum.osm-verkehrswende.org/project-vector-tiles/#18.77/52.6331382/13.2896622

funktioniert aber...

**Comment by gislars** [comment]
Objekte mit level=* oder layer=* wurden ausgeschlossen. layer ist jetzt kein Ausschlusskriterium mehr.

**Comment by SupaplexOSM** [comment]
`level` würde ich ebenfalls nicht ausschließen, oder welche Situation willst du damit vermeiden? Übereinanderliegende Daten in Parkhäusern oder so? Sollten wir sowas dann nicht auf anderen Wegen ausschließen?
Es ist durchaus legitim, eine Straße mit `level` auszustatten (z.B. eine Straße, die "durch ein Gebäude" führt und sozusagen an das Etagensystem des Gebäudes angebunden ist), auch wenn es meist wohl eher falsch verwendet wird. Aber das kommt noch dazu: Inflationäres verwenden von `level=*` ist ein häufiger "Mappingfehler" und es wäre ärgerlich, dann unnötigerweise Daten zu verlieren. In Berlin gibt es übrigens [300 Straßen-ways](https://overpass-turbo.eu/s/1jHF), die ein `level` tragen.

**Comment by gislars** [comment]
Den Filter auf `level` und `layer` hatte ich von Anfang an drin, ohne an einen bestimmten Fall zu denken. An Brücken hatte ich nicht gedacht. 
`level` ist jetzt auch entfernt.

**Comment by SupaplexOSM** [comment]
Ich mach hier erstmal zu, oder?
