### ISSUE TITLE
Fußgängerübergänge ausstanzen

### ISSUE THREAD

**Issue by tordans** [gislars/strassenraum-berlin#3]
Wo Fußgängerübergänge gemapped sind, darf nicht geparkt werden. Diese Bereiche müssen aus der Park-Linie ausgestanzt werden.

Dafür müssen die Punkte mit Buffer erst dupliziert, dann mit dem gleichen Offset, der auch für die Park-Linie verwendet wird, verschoben werden. Anschließen kann gestanzt werden.

Aktuelle Anzeige (ohne Duplizierung):
![image](https://user-images.githubusercontent.com/111561/165974732-8ced9e6f-171e-44f6-a2d5-41e8beb628f1.png)

**Comment by gislars** [comment]
Fußgängerübergänge werden berücksichtigt.
