### ISSUE TITLE
Mobil-ansicht ist leer

### ISSUE THREAD

**Issue by joshinils** [gislars/strassenraum-berlin#36]
![Screenshot_20220702-133840_Firefox.png](https://user-images.githubusercontent.com/34302971/176999235-b9c2d77e-d3e2-4357-8ece-c2d713fc2192.png)

https://parkraum.osm-verkehrswende.org/project-vector-tiles/#16/52.47928/13.4381

Android 12, galaxy s10 mit firefox und chrome

**Comment by tordans** [comment]
Bitte nochmal testen, das müsste jetzt behoben sein.

**Comment by joshinils** [comment]
ja, sieht gut aus
